/**
 * ADMIN VIDEOS API - Database-powered video management
 * 
 * PURPOSE:
 * This API handles CRUD operations for YouTube videos using the Prisma database.
 * Videos are stored with metadata and linked to the broader course system.
 * 
 * WHAT THIS MODULE DOES:
 * - GET: Fetches all videos from database
 * - POST: Adds new YouTube videos with metadata extraction
 * - DELETE: Removes videos from database
 * - YouTube URL processing and thumbnail generation
 * 
 * RELATED MODULES TO UNDERSTAND:
 * - /prisma/schema.prisma - Video model definition
 * - /app/admin/videos/page.tsx - Admin video management UI
 * - /app/videos/[id]/page.tsx - Video player interface
 * - /lib/db.ts - Prisma database connection
 * - /data/videos.json - Legacy storage (migrated to database)
 * 
 * DATABASE RELATIONSHIPS:
 * - Video has many Quiz (linked via videoId)
 * - Video contains YouTube metadata (title, keywords, etc.)
 * - Video integrates with course/lecture system
 * 
 * ARCHITECTURE NOTE:
 * This API was migrated from JSON file storage to Prisma database for:
 * - Better integration with quiz and course systems
 * - Referential integrity and proper relationships
 * - Scalable video management and search capabilities
 * - Consistent data storage across the platform
 */

import { NextRequest, NextResponse } from 'next/server';
import { PrismaClient } from '@prisma/client';
export const dynamic = 'force-dynamic';

const prisma = new PrismaClient();

/**
 * TYPE DEFINITIONS AND CONSTANTS
 * Types are auto-generated by Prisma from the database schema.
 * See /prisma/schema.prisma for Video model definition.
 */

// YouTube URL patterns for video ID extraction
const YOUTUBE_URL_PATTERNS = [
  /(?:youtube\.com\/watch\?v=|youtu\.be\/|youtube\.com\/embed\/)([^&\n?#]+)/,
  /youtube\.com\/v\/([^&\n?#]+)/,
  /youtube\.com\/shorts\/([^&\n?#]+)/
];

// Video metadata defaults
const DEFAULT_THUMBNAIL_BASE = 'https://img.youtube.com/vi';
const DEFAULT_VIEWS = 0;

/**
 * DATABASE UTILITY FUNCTIONS
 * Helper functions for video operations and YouTube integration
 */

// Extract YouTube video ID from various URL formats
const extractYouTubeVideoId = (url: string): string => {
  for (const pattern of YOUTUBE_URL_PATTERNS) {
    const match = url.match(pattern);
    if (match && match[1]) {
      return match[1];
    }
  }
  return '';
};

// Generate YouTube thumbnail URL
const generateThumbnailUrl = (videoId: string, quality: 'default' | 'hqdefault' | 'maxresdefault' = 'hqdefault'): string => {
  return `${DEFAULT_THUMBNAIL_BASE}/${videoId}/${quality}.jpg`;
};

// Create keywords JSON from video metadata
const createVideoKeywords = (instructor: string, subject: string, description: string): string => {
  return JSON.stringify({
    instructor,
    subject,
    description,
    tags: [instructor, subject].filter(Boolean)
  });
};


/**
 * GET VIDEOS ENDPOINT
 * 
 * QUERY PARAMETERS:
 * - subject: Filter videos by subject (optional)
 * - instructor: Filter videos by instructor (optional)
 * 
 * RESPONSE FORMAT:
 * {
 *   success: true,
 *   videos: Video[] // with parsed keywords and metadata
 * }
 * 
 * DATABASE QUERIES:
 * - Uses Prisma to fetch videos with optional filtering
 * - Includes related quiz count for each video
 * - Returns formatted data for admin interface
 */
export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const subject = searchParams.get('subject');
    const instructor = searchParams.get('instructor');

    // Build dynamic where clause for filtering
    const whereClause: any = {};
    if (subject || instructor) {
      // Filter by keywords JSON content
      const keywordFilters = [];
      if (subject) keywordFilters.push(`"subject":"${subject}"`);
      if (instructor) keywordFilters.push(`"instructor":"${instructor}"`);
      
      // Use JSON contains filtering (SQLite compatible)
      whereClause.keywords = {
        contains: keywordFilters.join('')
      };
    }

    const videos = await prisma.video.findMany({
      where: whereClause,
      include: {
        quizzes: {
          select: { id: true }
        }
      },
      orderBy: { createdAt: 'desc' }
    });

    // Transform videos to include parsed metadata
    const transformedVideos = videos.map(video => {
      let parsedKeywords = {};
      try {
        parsedKeywords = JSON.parse(video.keywords);
      } catch (e) {
        console.warn(`Failed to parse keywords for video ${video.id}`);
      }

      return {
        id: video.youtubeId,
        title: video.title,
        thumbnail: generateThumbnailUrl(video.youtubeId),
        quizCount: video.quizzes.length,
        createdAt: video.createdAt,
        ...parsedKeywords
      };
    });

    return NextResponse.json({ 
      success: true, 
      videos: transformedVideos,
      total: transformedVideos.length
    });
  } catch (error) {
    console.error('Error fetching videos:', error);
    return NextResponse.json(
      { success: false, error: 'Failed to fetch videos' },
      { status: 500 }
    );
  } finally {
    await prisma.$disconnect();
  }
}

/**
 * POST CREATE VIDEO ENDPOINT
 * 
 * REQUEST BODY:
 * {
 *   videoUrl: string,    // YouTube URL
 *   title: string,       // Video title
 *   instructor: string,  // Instructor name
 *   subject: string,     // Subject/topic
 *   description: string, // Video description
 *   duration?: string    // Video duration (optional)
 * }
 * 
 * VALIDATION:
 * - Extracts and validates YouTube video ID from URL
 * - Checks for duplicate videos in database
 * - Validates required fields
 * 
 * DATABASE OPERATIONS:
 * - Creates Video record with proper metadata
 * - Stores keywords as JSON for search functionality
 * - Generates thumbnail URL automatically
 */
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { videoUrl, title, instructor, subject, description, duration } = body;

    // Validate required fields
    if (!videoUrl || !title || !instructor || !subject || !description) {
      return NextResponse.json(
        { success: false, error: 'Required fields: videoUrl, title, instructor, subject, description' },
        { status: 400 }
      );
    }

    // Extract video ID from URL
    const youtubeId = extractYouTubeVideoId(videoUrl);
    if (!youtubeId) {
      return NextResponse.json(
        { success: false, error: 'Invalid YouTube URL. Please provide a valid YouTube video URL.' },
        { status: 400 }
      );
    }

    // Check if video already exists in database
    const existingVideo = await prisma.video.findUnique({
      where: { youtubeId }
    });

    if (existingVideo) {
      return NextResponse.json(
        { success: false, error: 'Video already exists in library' },
        { status: 409 }
      );
    }

    // Create keywords JSON for search and filtering
    const keywords = createVideoKeywords(instructor, subject, description);

    // Create new video in database
    const newVideo = await prisma.video.create({
      data: {
        youtubeId,
        title,
        keywords
      },
      include: {
        quizzes: {
          select: { id: true }
        }
      }
    });

    // Transform response to match expected format
    const responseVideo = {
      id: newVideo.youtubeId,
      title: newVideo.title,
      instructor,
      subject,
      description,
      duration: duration || 'Unknown',
      thumbnail: generateThumbnailUrl(newVideo.youtubeId),
      quizCount: newVideo.quizzes.length,
      createdAt: newVideo.createdAt
    };

    return NextResponse.json({
      success: true,
      message: 'Video added successfully',
      video: responseVideo
    });

  } catch (error) {
    console.error('Error adding video:', error);
    return NextResponse.json(
      { success: false, error: 'Failed to add video' },
      { status: 500 }
    );
  } finally {
    await prisma.$disconnect();
  }
}

/**
 * DELETE VIDEO ENDPOINT
 * 
 * QUERY PARAMETERS:
 * - id: YouTube video ID to delete
 * 
 * VALIDATION:
 * - Checks if video exists in database
 * - Verifies no associated quizzes exist (referential integrity)
 * 
 * DATABASE OPERATIONS:
 * - Deletes Video record from database
 * - Handles cascading relationships properly
 * - Returns confirmation of deletion
 */
export async function DELETE(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const youtubeId = searchParams.get('id');

    if (!youtubeId) {
      return NextResponse.json(
        { success: false, error: 'Video ID is required' },
        { status: 400 }
      );
    }

    // Check if video exists and get associated data
    const video = await prisma.video.findUnique({
      where: { youtubeId },
      include: {
        quizzes: {
          select: { id: true }
        }
      }
    });

    if (!video) {
      return NextResponse.json(
        { success: false, error: 'Video not found' },
        { status: 404 }
      );
    }

    // Check if video has associated quizzes
    if (video.quizzes.length > 0) {
      return NextResponse.json(
        { 
          success: false, 
          error: `Cannot delete video: ${video.quizzes.length} quiz(es) are associated with this video. Delete quizzes first.` 
        },
        { status: 409 }
      );
    }

    // Delete the video
    await prisma.video.delete({
      where: { youtubeId }
    });

    return NextResponse.json({
      success: true,
      message: 'Video deleted successfully'
    });

  } catch (error) {
    console.error('Error deleting video:', error);
    return NextResponse.json(
      { success: false, error: 'Failed to delete video' },
      { status: 500 }
    );
  } finally {
    await prisma.$disconnect();
  }
}
