/**
 * ASSIGNMENT SUBMISSIONS API - Database-powered submission management
 * 
 * PURPOSE:
 * This API handles student assignment submissions and teacher feedback using
 * the Prisma database. Students upload PDF files, and teachers provide grades/comments.
 * 
 * WHAT THIS MODULE DOES:
 * - GET: Fetches submissions (filtered by assignment, student, or teacher)
 * - POST: Handles file uploads (action=submit) and teacher feedback (action=feedback)
 * - File processing: PDF text extraction and validation
 * - Status tracking: SUBMITTED → GRADED → RETURNED
 * 
 * RELATED MODULES TO UNDERSTAND:
 * - /prisma/schema.prisma - AssignmentSubmission, AssignmentFeedback models
 * - /app/api/assignments/route.ts - Assignment management (linked data)
 * - /app/student-assignments/page.tsx - Student submission UI
 * - /lib/db.ts - Prisma database connection
 * - File storage: /uploads/assignments/ directory for PDF files
 * 
 * DATABASE RELATIONSHIPS:
 * - AssignmentSubmission belongs to Assignment (assignmentId foreign key)
 * - AssignmentSubmission belongs to User (studentId foreign key)
 * - AssignmentSubmission has one optional AssignmentFeedback
 * - AssignmentFeedback belongs to User (teacherId foreign key)
 * 
 * ARCHITECTURE NOTE:
 * This API was migrated from JSON file storage to Prisma database for:
 * - Atomic transactions (submission + feedback)
 * - Referential integrity (can't submit to non-existent assignment)
 * - Better concurrent file upload handling
 * - Integration with user and assignment systems
 */

import { NextRequest, NextResponse } from 'next/server';
import { PrismaClient } from '@prisma/client';
import fs from 'fs';
import path from 'path';

const prisma = new PrismaClient();

// Import PDF processing
let pdfParse: any;
try {
  pdfParse = require('pdf-parse/lib/pdf-parse.js');
} catch (e) {
  console.error('PDF parse import error:', e);
}

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

/**
 * TYPE DEFINITIONS AND CONSTANTS
 * Types are auto-generated by Prisma from database schema.
 * See /prisma/schema.prisma for AssignmentSubmission and AssignmentFeedback models.
 */

// File upload constants
const MAX_FILE_SIZE = 10 * 1024 * 1024; // 10MB limit
const ALLOWED_FILE_TYPES = ['application/pdf'];
const UPLOAD_DIR = 'uploads/assignments';

/**
 * DATABASE UTILITY FUNCTIONS
 * Helper functions for submission queries and file operations
 */

// Ensure upload directory exists
const ensureUploadDirectory = () => {
  const uploadsDir = path.join(process.cwd(), UPLOAD_DIR);
  if (!fs.existsSync(uploadsDir)) {
    fs.mkdirSync(uploadsDir, { recursive: true });
  }
  return uploadsDir;
};

// Check if assignment is late based on due date
const isSubmissionLate = async (assignmentId: string): Promise<boolean> => {
  const assignment = await prisma.assignment.findUnique({
    where: { id: assignmentId },
    select: { dueDate: true }
  });
  
  if (!assignment) return false;
  return new Date() > assignment.dueDate;
};

// Generate secure filename for uploaded files
const generateSecureFilename = (originalName: string, studentId: string): string => {
  const timestamp = Date.now();
  const sanitizedName = originalName.replace(/[^a-zA-Z0-9.-]/g, '_');
  return `${timestamp}_${studentId}_${sanitizedName}`;
};


// Extract text from PDF using OCR-like processing
const extractTextFromPDF = async (pdfBuffer: Buffer): Promise<string> => {
  try {
    if (!pdfParse) {
      throw new Error('PDF parser not available');
    }
    
    const data = await pdfParse(pdfBuffer);
    return data.text || '';
  } catch (error) {
    console.error('Error extracting text from PDF:', error);
    return '';
  }
};

/**
 * GET SUBMISSIONS ENDPOINT
 * 
 * QUERY PARAMETERS:
 * - assignmentId: Get all submissions for specific assignment
 * - studentId: Get all submissions by specific student
 * - teacherId: Get submissions for teacher's classes
 * 
 * RESPONSE FORMAT:
 * {
 *   success: true,
 *   submissions: AssignmentSubmission[] // with feedback and assignment info
 * }
 * 
 * DATABASE QUERIES:
 * - Uses Prisma to fetch submissions with related data
 * - Includes assignment info, student info, and feedback
 * - Proper filtering based on user role and permissions
 */
export async function GET(req: NextRequest) {
  try {
    const { searchParams } = new URL(req.url);
    const assignmentId = searchParams.get('assignmentId');
    const studentId = searchParams.get('studentId');
    const teacherId = searchParams.get('teacherId');

    // Build dynamic query based on parameters
    const whereClause: any = {};
    if (assignmentId) whereClause.assignmentId = assignmentId;
    if (studentId) whereClause.studentId = studentId;
    
    // If teacher is requesting, filter by their classes
    if (teacherId) {
      // For now, include all submissions. In production, filter by teacher's classes
      // whereClause.assignment = { class: { center: { tutors: { some: { id: teacherId } } } } };
    }

    const submissions = await prisma.assignmentSubmission.findMany({
      where: whereClause,
      include: {
        assignment: {
          select: {
            title: true,
            dueDate: true,
            maxPoints: true,
            class: {
              select: { name: true }
            }
          }
        },
        feedback: true
      },
      orderBy: { submittedAt: 'desc' }
    });
    
    return NextResponse.json({
      success: true,
      submissions
    });

  } catch (error: any) {
    console.error('Error fetching submissions:', error);
    return NextResponse.json({
      success: false,
      error: error.message
    }, { status: 500 });
  } finally {
    await prisma.$disconnect();
  }
}

/**
 * POST SUBMISSIONS ENDPOINT
 * 
 * ACTIONS:
 * - submit: Student uploads assignment file
 * - feedback: Teacher provides grade and comments
 * 
 * REQUEST FORMAT (FormData):
 * For submit: { action: 'submit', file: File, assignmentId: string, studentId: string }
 * For feedback: { action: 'feedback', submissionId: string, teacherId: string, grade?: number, comments?: string }
 * 
 * DATABASE OPERATIONS:
 * - Creates AssignmentSubmission with file metadata
 * - Creates AssignmentFeedback linked to submission
 * - Uses transactions for data consistency
 * - Handles duplicate submissions (updates existing)
 */
export async function POST(req: NextRequest) {
  try {
    const formData = await req.formData();
    const action = formData.get('action') as string;

    if (action === 'submit') {
      // Handle file upload and submission
      const file = formData.get('file') as File;
      const assignmentId = formData.get('assignmentId') as string;
      const studentId = formData.get('studentId') as string;

      if (!file || !assignmentId || !studentId) {
        return NextResponse.json({
          success: false,
          error: 'Missing required fields: file, assignmentId, studentId'
        }, { status: 400 });
      }

      // Validate file type and size
      if (!ALLOWED_FILE_TYPES.includes(file.type)) {
        return NextResponse.json({
          success: false,
          error: 'Only PDF files are allowed'
        }, { status: 400 });
      }

      if (file.size > MAX_FILE_SIZE) {
        return NextResponse.json({
          success: false,
          error: 'File size exceeds 10MB limit'
        }, { status: 400 });
      }

      // Verify assignment exists
      const assignment = await prisma.assignment.findUnique({
        where: { id: assignmentId },
        select: { id: true, dueDate: true, title: true }
      });

      if (!assignment) {
        return NextResponse.json({
          success: false,
          error: 'Assignment not found'
        }, { status: 404 });
      }

      // Prepare file storage
      const uploadsDir = ensureUploadDirectory();
      const filename = generateSecureFilename(file.name, studentId);
      const filePath = path.join(uploadsDir, filename);

      // Save file to disk
      const buffer = Buffer.from(await file.arrayBuffer());
      fs.writeFileSync(filePath, buffer);

      // Extract text from PDF
      const extractedText = await extractTextFromPDF(buffer);

      // Check if submission is late
      const isLate = await isSubmissionLate(assignmentId);
      const status = isLate ? 'LATE' : 'SUBMITTED';

      // Check for existing submission (upsert behavior)
      const existingSubmission = await prisma.assignmentSubmission.findFirst({
        where: {
          assignmentId,
          studentId
        }
      });

      let submission;
      
      if (existingSubmission) {
        // Update existing submission
        submission = await prisma.assignmentSubmission.update({
          where: { id: existingSubmission.id },
          data: {
            filePath: path.relative(process.cwd(), filePath),
            fileName: file.name,
            fileSize: file.size,
            extractedText,
            status,
            submittedAt: new Date()
          },
          include: {
            assignment: {
              select: { title: true, dueDate: true }
            }
          }
        });
      } else {
        // Create new submission
        submission = await prisma.assignmentSubmission.create({
          data: {
            assignmentId,
            studentId,
            filePath: path.relative(process.cwd(), filePath),
            fileName: file.name,
            fileSize: file.size,
            extractedText,
            status
          },
          include: {
            assignment: {
              select: { title: true, dueDate: true }
            }
          }
        });
      }

      return NextResponse.json({
        success: true,
        submission: {
          ...submission,
          extractedTextPreview: extractedText.substring(0, 200) + '...'
        }
      });

    } else if (action === 'feedback') {
      // Handle teacher feedback using database
      const submissionId = formData.get('submissionId') as string;
      const teacherId = formData.get('teacherId') as string;
      const grade = formData.get('grade') as string;
      const comments = formData.get('comments') as string;

      if (!submissionId || !teacherId) {
        return NextResponse.json({
          success: false,
          error: 'Missing required fields: submissionId, teacherId'
        }, { status: 400 });
      }

      // Verify submission exists
      const submission = await prisma.assignmentSubmission.findUnique({
        where: { id: submissionId },
        include: {
          assignment: {
            select: { title: true, maxPoints: true }
          },
          feedback: true
        }
      });

      if (!submission) {
        return NextResponse.json({
          success: false,
          error: 'Submission not found'
        }, { status: 404 });
      }

      // Use transaction to update submission status and create/update feedback
      const result = await prisma.$transaction(async (tx) => {
        // Update submission status
        const updatedSubmission = await tx.assignmentSubmission.update({
          where: { id: submissionId },
          data: { status: 'GRADED' }
        });

        // Create or update feedback
        const feedbackData = {
          submissionId,
          teacherId,
          grade: grade ? parseInt(grade) : null,
          comments: comments || null
        };

        let feedback;
        if (submission.feedback) {
          // Update existing feedback
          feedback = await tx.assignmentFeedback.update({
            where: { id: submission.feedback.id },
            data: feedbackData
          });
        } else {
          // Create new feedback
          feedback = await tx.assignmentFeedback.create({
            data: feedbackData
          });
        }

        return { submission: updatedSubmission, feedback };
      });

      return NextResponse.json({
        success: true,
        submission: {
          ...result.submission,
          feedback: result.feedback
        }
      });

    } else {
      return NextResponse.json({
        success: false,
        error: 'Invalid action'
      }, { status: 400 });
    }

  } catch (error: any) {
    console.error('Error processing submission:', error);
    return NextResponse.json({
      success: false,
      error: error.message
    }, { status: 500 });
  } finally {
    await prisma.$disconnect();
  }
}
