/**
 * ASSIGNMENTS API - Database-powered assignment management
 * 
 * PURPOSE:
 * This API handles CRUD operations for assignments using the Prisma database.
 * Assignments are course-specific tasks that students submit and teachers grade.
 * 
 * WHAT THIS MODULE DOES:
 * - GET: Fetches assignments (optionally filtered by class or student)
 * - POST: Creates new assignments for classes
 * - Integrates with submission system for student progress tracking
 * 
 * RELATED MODULES TO UNDERSTAND:
 * - /prisma/schema.prisma - Assignment, AssignmentSubmission, Class models
 * - /app/api/assignment-submissions/route.ts - Student submission handling
 * - /app/assignments/page.tsx - Student assignment view UI
 * - /app/dashboard/parts/Student.tsx - Assignment integration in dashboard
 * - /lib/db.ts - Prisma database connection
 * 
 * DATABASE RELATIONSHIPS:
 * - Assignment belongs to Class (classId foreign key)
 * - Assignment has many AssignmentSubmissions (one per student)
 * - AssignmentSubmission has optional AssignmentFeedback (grades/comments)
 * 
 * ARCHITECTURE NOTE:
 * This API was migrated from JSON file storage to Prisma database for:
 * - Data integrity and referential constraints
 * - Better performance and concurrent access
 * - Integration with other database models
 */

import { NextRequest, NextResponse } from 'next/server';
import { PrismaClient } from '@prisma/client';
export const dynamic = 'force-dynamic';

const prisma = new PrismaClient();

/**
 * TYPE DEFINITIONS
 * These types are now automatically generated by Prisma from the database schema.
 * See /prisma/schema.prisma for the source of truth.
 * 
 * Key types used:
 * - Assignment: Core assignment data (title, description, due date, etc.)
 * - AssignmentSubmission: Student file submissions linked to assignments
 * - AssignmentFeedback: Teacher grades and comments on submissions
 * - SubmissionStatus: SUBMITTED | GRADED | RETURNED | LATE
 */

/**
 * DATABASE UTILITY FUNCTIONS
 * Helper functions for common assignment queries and operations
 */

// Get assignments with submission status for a specific student
async function getAssignmentsWithSubmissionStatus(classId: string, studentId?: string) {
  const assignments = await prisma.assignment.findMany({
    where: { classId },
    include: {
      submissions: studentId ? {
        where: { studentId },
        include: { feedback: true }
      } : false,
      class: {
        select: { name: true }
      }
    },
    orderBy: { dueDate: 'asc' }
  });

  // Transform to include submission status directly in assignment object
  if (studentId) {
    return assignments.map(assignment => {
      const sub = assignment.submissions[0];
      return {
        ...assignment,
        submissionStatus: sub?.status || null,
        submittedAt: sub?.submittedAt || null,
        feedback: sub && 'feedback' in sub ? (sub as { feedback: unknown }).feedback : null
      };
    });
  }

  return assignments;
}

/**
 * GET ASSIGNMENTS ENDPOINT
 * 
 * QUERY PARAMETERS:
 * - classId: Filter assignments by specific class
 * - studentId: Include submission status for specific student
 * 
 * RESPONSE FORMAT:
 * {
 *   success: true,
 *   assignments: Assignment[] // with submission status if studentId provided
 * }
 * 
 * DATABASE QUERIES:
 * - Uses Prisma to fetch assignments with related data
 * - Includes class info and submission status efficiently
 * - Proper ordering by due date
 */
export async function GET(req: NextRequest) {
  try {
    const { searchParams } = new URL(req.url);
    const classId = searchParams.get('classId');
    const studentId = searchParams.get('studentId');

    // Validate required classId parameter
    if (!classId) {
      return NextResponse.json({
        success: false,
        error: 'classId parameter is required'
      }, { status: 400 });
    }

    // Fetch assignments with optional student submission status
    const assignments = await getAssignmentsWithSubmissionStatus(classId, studentId || undefined);

    return NextResponse.json({
      success: true,
      assignments
    });

  } catch (error: any) {
    console.error('Error fetching assignments:', error);
    return NextResponse.json({
      success: false,
      error: error.message
    }, { status: 500 });
  } finally {
    await prisma.$disconnect();
  }
}

/**
 * POST CREATE ASSIGNMENT ENDPOINT
 * 
 * REQUEST BODY:
 * {
 *   title: string,
 *   description: string,
 *   classId: string,
 *   createdBy: string, // Teacher user ID
 *   dueDate: string,   // ISO date string
 *   maxPoints?: number // defaults to 100
 * }
 * 
 * VALIDATION:
 * - Ensures class exists before creating assignment
 * - Validates due date is in the future
 * - Checks that createdBy user has permission for this class
 * 
 * DATABASE OPERATIONS:
 * - Creates Assignment record with proper relationships
 * - Uses Prisma-generated unique IDs
 * - Maintains referential integrity
 */
export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const { title, description, classId, createdBy, dueDate, maxPoints = 100 } = body;

    // Validate required fields
    if (!title || !description || !classId || !createdBy || !dueDate) {
      return NextResponse.json({
        success: false,
        error: 'Missing required fields: title, description, classId, createdBy, dueDate'
      }, { status: 400 });
    }

    // Validate due date format and ensure it's in the future
    const dueDateObj = new Date(dueDate);
    if (isNaN(dueDateObj.getTime())) {
      return NextResponse.json({
        success: false,
        error: 'Invalid due date format. Please use ISO date string.'
      }, { status: 400 });
    }

    // Verify the class exists
    const classExists = await prisma.class.findUnique({
      where: { id: classId }
    });

    if (!classExists) {
      return NextResponse.json({
        success: false,
        error: 'Class not found'
      }, { status: 404 });
    }

    // Create the assignment in the database
    const newAssignment = await prisma.assignment.create({
      data: {
        title,
        description,
        classId,
        createdBy,
        dueDate: dueDateObj,
        maxPoints
      },
      include: {
        class: {
          select: { name: true }
        }
      }
    });

    return NextResponse.json({
      success: true,
      assignment: newAssignment
    });

  } catch (error: any) {
    console.error('Error creating assignment:', error);
    return NextResponse.json({
      success: false,
      error: error.message
    }, { status: 500 });
  } finally {
    await prisma.$disconnect();
  }
}
